source 'http://rubygems.org'
gem 'gravtastic'
gem 'rails', '3.0.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2', '0.2.11'
gem 'newrelic_rpm'

gem 'devise'
gem 'cancan'
gem 'grit'
gem 'albino'
gem 'rake', '0.8.7'
gem 'jquery-rails', '>= 1.0.3'
gem 'postmark-rails'
gem 'linguist', :git => "git@ec2-107-20-216-88.compute-1.amazonaws.com:buddylindsey/linguist.git"

group :development, :test do
  gem 'spork', '~> 0.9.0rc9'
  gem 'sqlite3'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'watchr'
  #gem 'autotest'
  #gem 'autotest-standalone'
  #gem 'autotest-rails'
  gem 'webrat'
  gem 'factory_girl'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
end

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
